"""Differentiable near-axis stellarator construction in JAX."""

from pyqsc_jax.axis import Axis
from pyqsc_jax.diagnostics import mercier_diagnostics
from pyqsc_jax.field import total_field_jet
from pyqsc_jax.first_order import Qsc, solve
from pyqsc_jax.models import (
    FieldJet,
    LinearSolveReport,
    MercierDiagnostics,
    NearAxisInputs,
    NearAxisSolution,
    RootSolveReport,
    SecondOrderData,
    SingularityDiagnostics,
    ThirdOrderData,
)
from pyqsc_jax.near_axis import near_axis
from pyqsc_jax.optimize import (
    B2cOptimizationResult,
    B20Diagnostics,
    b20_diagnostics,
    optimal_B2c_value,
    optimize_B2c,
)
from pyqsc_jax.plasma import (
    PlasmaCurrentSource,
    PlasmaFieldData,
    PlasmaGradientData,
    PlasmaHessianData,
    covariant_current_from_enclosed,
    elliptical_channel_gradient,
    enclosed_current_from_covariant,
    evaluate_weighted_current,
    matched_plasma_field_kernel,
    pack_symmetric_trace_free_rank2,
    pack_symmetric_trace_free_rank3,
    plasma_current_source,
    plasma_field_on_axis,
    plasma_gradient_on_axis,
    plasma_hessian_on_axis,
    project_symmetric_trace_free_rank2,
    project_symmetric_trace_free_rank3,
    regularized_axis_integral,
    unpack_symmetric_trace_free_rank2,
    unpack_symmetric_trace_free_rank3,
)
from pyqsc_jax.second_order import SecondOrderResiduals, second_order_residuals
from pyqsc_jax.singularity import singularity_diagnostics
from pyqsc_jax.solvers import RootSolveOptions
from pyqsc_jax.third_order import solve_third_order
from pyqsc_jax.vmec import (
    VmecBoundary,
    VmecExport,
    VmecInputParameters,
    to_vmec,
    uniform_cylindrical_surface,
    vmec_boundary,
)
from pyqsc_jax.vmex import (
    VMEX_VALIDATED_COMMIT,
    VmexEquilibrium,
    VmexProblem,
    VmexRadialQuantities,
    solve_vmex,
    to_vmex_problem,
    vmex_parameters_from_solution,
    vmex_radial_quantities,
)

__all__ = [
    "Axis",
    "B2cOptimizationResult",
    "B20Diagnostics",
    "FieldJet",
    "LinearSolveReport",
    "MercierDiagnostics",
    "NearAxisInputs",
    "NearAxisSolution",
    "PlasmaCurrentSource",
    "PlasmaFieldData",
    "PlasmaGradientData",
    "PlasmaHessianData",
    "Qsc",
    "RootSolveOptions",
    "RootSolveReport",
    "SecondOrderData",
    "SecondOrderResiduals",
    "SingularityDiagnostics",
    "ThirdOrderData",
    "VmecBoundary",
    "VmecExport",
    "VmecInputParameters",
    "VmexEquilibrium",
    "VmexProblem",
    "VmexRadialQuantities",
    "VMEX_VALIDATED_COMMIT",
    "near_axis",
    "b20_diagnostics",
    "covariant_current_from_enclosed",
    "enclosed_current_from_covariant",
    "elliptical_channel_gradient",
    "evaluate_weighted_current",
    "matched_plasma_field_kernel",
    "pack_symmetric_trace_free_rank2",
    "pack_symmetric_trace_free_rank3",
    "mercier_diagnostics",
    "second_order_residuals",
    "solve",
    "singularity_diagnostics",
    "solve_third_order",
    "total_field_jet",
    "to_vmec",
    "to_vmex_problem",
    "uniform_cylindrical_surface",
    "vmec_boundary",
    "vmex_parameters_from_solution",
    "vmex_radial_quantities",
    "solve_vmex",
    "optimal_B2c_value",
    "optimize_B2c",
    "plasma_current_source",
    "plasma_field_on_axis",
    "plasma_gradient_on_axis",
    "plasma_hessian_on_axis",
    "project_symmetric_trace_free_rank2",
    "project_symmetric_trace_free_rank3",
    "regularized_axis_integral",
    "unpack_symmetric_trace_free_rank2",
    "unpack_symmetric_trace_free_rank3",
]
__version__ = "0.2.0.dev0"
